version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wdd-php-server
    restart: always
    ports:
      - 4000:80
    volumes:
      - ..:/var/www/html
volumes:
  html: {}